spring:
  application:
    name: CloudFileOrganizer
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_file_db
    username: postgres
    password: ${DB_PASSWORD:Sarath18}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false

server:
  port: 8080

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    url-expiration-minutes: 60

gemini:
  api-key: ${GEMINI_API_KEY}
  url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent
  retry:
    max-attempts: 3
    backoff-period: 2000

ai:
  analysis:
    enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.cloudfileorganizer: DEBUG
